{
 "title": "Total Sales",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Sales by Product Today",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select sum(p.price), count(*), i.name from default.purchases p join `service_e2e-cdc-service-pg_defaultdb_public`.item i on p.item_id = i.id \nwhere toDayOfYear(p.order_placed) = toDayOfYear(today())\ngroup by i.name order by 1 desc",
     "rawQuery": "select sum(p.price), count(*), i.name from default.purchases p join `service_e2e-cdc-service-pg_defaultdb_public`.item i on p.item_id = i.id \nwhere toDayOfYear(p.order_placed) = toDayOfYear(today())\ngroup by i.name order by 1 desc",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total Sales today",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select i.name, sum(p.price), sum(p.total_quantity) \n   from default.purchases p join `service_e2e-cdc-service-pg_defaultdb_public`.item i on p.item_id = i.id \n   where toDayOfYear(order_placed) = toDayOfYear(today())\ngroup by i.name order by 1 desc",
     "rawQuery": "select i.name, sum(p.price), sum(p.total_quantity) \n   from default.purchases p join `service_e2e-cdc-service-pg_defaultdb_public`.item i on p.item_id = i.id \n   where toDayOfYear(order_placed) = toDayOfYear(today())\ngroup by i.name order by 1 desc",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Sales today",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    s.name,\n    sum(p.price),\n    count(*),\n    s.latitude as lat,\n    s.longitude as lon\nFROM default.purchases p\n\nJOIN \n \n    `service_e2e-cdc-service-pg_defaultdb_public` \n    . \n    store \n    s ON  p.store_id=s.id\nwhere toDayOfYear(p.order_placed) = toDayOfYear(today())\nGROUP BY\n    s.name,\n    s.latitude,\n    s.longitude\nORDER BY 2 desc\n",
     "rawQuery": "SELECT\n    s.name,\n    sum(p.price),\n    count(*),\n    s.latitude as lat,\n    s.longitude as lon\nFROM default.purchases p\n\nJOIN \n \n    `service_e2e-cdc-service-pg_defaultdb_public` \n    . \n    store \n    s ON  p.store_id=s.id\nwhere toDayOfYear(p.order_placed) = toDayOfYear(today())\nGROUP BY\n    s.name,\n    s.latitude,\n    s.longitude\nORDER BY 2 desc",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total Sales  by Product",
   "type": "barchart",
   "description": "Total Sales and count of items sold",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select sum(p.price), count(*), i.name from default.purchases p join `service_e2e-cdc-service-pg_defaultdb_public`.item i on p.item_id = i.id \ngroup by i.name order by 1 desc",
     "rawQuery": "select sum(p.price), count(*), i.name from default.purchases p join `service_e2e-cdc-service-pg_defaultdb_public`.item i on p.item_id = i.id \ngroup by i.name order by 1 desc",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Sales this year by Month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select toMonth(p.order_placed) as monthNum, monthName(p.order_placed) as month, sum(p.price) from purchases p where toYear(p.order_placed) = 2023 group by month, monthNum order by monthNum",
     "rawQuery": "select toMonth(p.order_placed) as monthNum, monthName(p.order_placed) as month, sum(p.price) from purchases p where toYear(p.order_placed) = 2023 group by month, monthNum order by monthNum",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Top 10 Stores today",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select sum(p.price), count(*), s.name from default.purchases p join `service_e2e-cdc-service-pg_defaultdb_public`.store s on p.store_id = s.id \nwhere toDayOfYear(order_placed) = toDayOfYear(today())\ngroup by s.name order by 1 desc limit 10",
     "rawQuery": "select sum(p.price), count(*), s.name from default.purchases p join `service_e2e-cdc-service-pg_defaultdb_public`.store s on p.store_id = s.id \nwhere toDayOfYear(order_placed) = toDayOfYear(today())\ngroup by s.name order by 1 desc limit 10",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Top 10 Stores of All Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select sum(p.price), count(*), s.name from default.purchases p join `service_e2e-cdc-service-pg_defaultdb_public`.store s on p.store_id = s.id \ngroup by s.name order by 1 desc limit 10",
     "rawQuery": "select sum(p.price), count(*), s.name from default.purchases p join `service_e2e-cdc-service-pg_defaultdb_public`.store s on p.store_id = s.id \ngroup by s.name order by 1 desc limit 10",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total Sales by Year",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select sum(p.price), toYear(p.order_placed) as year from purchases p where year > 1970 group by year order by 1 desc",
     "rawQuery": "select sum(p.price), toYear(p.order_placed) as year from purchases p where year > 1970 group by year order by 1 desc",
     "round": "0s"
    }
   ]
  }
 ]
}